### ISSUE TITLE
Want money?

### ISSUE THREAD

**Issue by 2516455367** [IDEA-Research/DINO-X-API#10]
There is nothing in the project.

**Comment by rentainhe** [comment]
Hello, training such a large model requires significant resources and effort. We are a startup team, and we need to explore commercialization from certain angles. We completely understand that you would like to use a free model, but we also hope you can understand the plans and decisions we are making for the future of our team. For now, the model will only be available through an API. We are in the process of refining the API usage guidelines, and currently, only some features are available. Open-sourcing the full model is not part of our current plans. We hope you can understand.
