### ISSUE TITLE
Request for Additional API Tokens for Testing DINO-X-API

### ISSUE THREAD

**Issue by zflyy** [IDEA-Research/DINO-X-API#17]
Dear @rentainhe,

Thank you for providing such a great resource with DINO-X-API. We are currently using it for testing purposes, but we have encountered an issue with the token limit. The default 200 tokens are insufficient for our testing needs.

We have already tried the following steps to request additional tokens:

Submitted a request for more tokens via the Deep Data Space website, but we have not received any response.
Sent an email to rentianhe@idea.edu.cn with our request, but unfortunately, we did not receive a reply either.
Our project heavily relies on this API, and the current token limit has become a bottleneck for our progress. We would greatly appreciate it if we could receive more tokens, even if it involves purchasing them.

Could you please let us know the next steps to obtain additional tokens? Thank you very much for your attention and support.

**Comment by rentainhe** [comment]
Would you like to provide your email address (registered on our official website for API token usage) to us. I have checked my   outlook many times and did not see any emails about additional token application. I'm not sure why this situation has occurred. If it's not too much trouble, could you please send another email detailing the additional number of tokens you require? I will forward this information to our relevant product colleagues for further coordination.

**Comment by zflyy** [comment]
Dear @rentianhe,

Thank you very much for your prompt reply. We truly appreciate your support.

Our registered email address on your official website for API token usage is 17844588655@163.com.

Currently, we require approximately 5,000 tokens for testing purposes. If this incurs any additional fees, please do not hesitate to inform us—we are more than willing to cover any necessary costs.

We guarantee that the tokens will be used strictly for academic research purposes. Additionally, we assure you that we will comply with all guidelines and policies regarding the usage of your API tokens.

Thank you once again for your kind assistance. Please feel free to let us know if you require any further information from our side.

**Comment by rentainhe** [comment]
Thanks you so much, we have already received your email and we will assign you additional 5000 tokens during working hours, thanks again for your support to our work.
