### ISSUE TITLE
Will the models and code pipeline be made open-source?

### ISSUE THREAD

**Issue by sovit-123** [IDEA-Research/DINO-X-API#2]
Hello. Great work. Appreciate everyone's effort involved in the project.

I wanted to enquire whether the model weights, code files, training, and evaluation pipeline will be made open source.

**Comment by rentainhe** [comment]
Hello @sovit-123 Hello, as we are currently exploring some commercialization opportunities, we will only provide access to our model through API for the time being.

**Comment by sovit-123** [comment]
Thanks for the update @rentainhe
All the best, I think this is an excellent project.
I am working on something like this but with multiple-model pipeline. Will expand the project with more tasks soon.
https://github.com/sovit-123/SAM_Molmo_Whisper

The main reason to choose multiple models is the ability to switch and improve to smaller models in the future. I want to bring the entire pipeline to below 1.5B parameters. Not sure whether that's possible though.

I am curious. How many parameters do the DINO-X pipeline models consist of? As I understood from the paper, the pipeline uses a single model with multiple heads. If you can share the parameter range or number it will be helpful for me to optimize my project as well. 

Again, all the best.

**Comment by rentainhe** [comment]
Hello @sovit-123 , DINO-X is a single model with multiple heads and only has less than 1B parameters.

**Comment by sovit-123** [comment]
Thanks for the reply @rentainhe. That's really an optimized pipeline.

**Comment by rentainhe** [comment]
> Thanks for the reply @rentainhe. That's really an optimized pipeline.

Thank you for your recognition of our work. To training multiple function into one model is a complex problem, and we are still improving our model towards better performance and more convenient usage.

**Comment by sovit-123** [comment]
Sure, that sounds great. All the best.
