### ISSUE TITLE
hand keypoints detection

### ISSUE THREAD

**Issue by ccchen091** [IDEA-Research/DINO-X-API#6]
Hello, I got the following error when using your API for hand key point detection, which is supposed to be caused by the model not detecting it. I would like to ask how this should be solved? The image I entered was a jpg format, which must contain the hands.

Traceback (most recent call last):
  File "/data/d1/chenhao/code/DINO-X-API-main/demo.py", line 76, in <module>
    detections = sv.Detections(
  File "<string>", line 9, in __init__
  File "/home/chenhao/anaconda3/envs/DINO-API/lib/python3.9/site-packages/supervision/detection/core.py", line 130, in __post_init__
    validate_detections_fields(
  File "/home/chenhao/anaconda3/envs/DINO-API/lib/python3.9/site-packages/supervision/validators/__init__.py", line 120, in validate_detections_fields
    validate_xyxy(xyxy)
  File "/home/chenhao/anaconda3/envs/DINO-API/lib/python3.9/site-packages/supervision/validators/__init__.py", line 11, in validate_xyxy
    raise ValueError(
ValueError: xyxy must be a 2D np.ndarray with shape (_, 4), but got shape (0,)

**Comment by rentainhe** [comment]
@ccchen091 Hello, we are still refining our API usage. And I think the issue you met is related to the visualization process, would you like to check if there are predicted boxes or not.

**Comment by ccchen091** [comment]
> @ccchen091 Hello, we are still refining our API usage. And I think the issue you met is related to the visualization process, would you like to check if there are predicted boxes or not.
I went to print out the "predictions" and found that the "predictions" were empty, which should be caused by the API not detecting the hand in the image, but I don't know why the model did not detect the hand in the image.

**Comment by rentainhe** [comment]
> > @ccchen091 Hello, we are still refining our API usage. And I think the issue you met is related to the visualization process, would you like to check if there are predicted boxes or not.
> > I went to print out the "predictions" and found that the "predictions" were empty, which should be caused by the API not detecting the hand in the image, but I don't know why the model did not detect the hand in the image.

would you like to provide us with your image and text prompt, which may be more convenient for us to solve this issue.

**Comment by ccchen091** [comment]
> > > @ccchen091 Hello, we are still refining our API usage. And I think the issue you met is related to the visualization process, would you like to check if there are predicted boxes or not.
> > > I went to print out the "predictions" and found that the "predictions" were empty, which should be caused by the API not detecting the hand in the image, but I don't know why the model did not detect the hand in the image.
> 
> would you like to provide us with your image and text prompt, which may be more convenient for us to solve this issue.

I'm very sorry. I found out that my text prompt was set incorrectly, and when I set the text prompt to "hand", it was able to detect correctly. Thank you for this excellent work. Thank you for your patience.

**Comment by rentainhe** [comment]
> > > > @ccchen091 Hello, we are still refining our API usage. And I think the issue you met is related to the visualization process, would you like to check if there are predicted boxes or not.
> > > > I went to print out the "predictions" and found that the "predictions" were empty, which should be caused by the API not detecting the hand in the image, but I don't know why the model did not detect the hand in the image.
> > 
> > 
> > would you like to provide us with your image and text prompt, which may be more convenient for us to solve this issue.
> 
> I'm very sorry. I found out that my text prompt was set incorrectly, and when I set the text prompt to "hand", it was able to detect correctly. Thank you for this excellent work. Thank you for your patience.

You're welcome, we are still updating our API usage, and trying to make it more convenient for the community users.
