### ISSUE TITLE
how to use prompt-free feature? Is there any demo.py about prompt-free?

### ISSUE THREAD

**Issue by xyl3902596** [IDEA-Research/DINO-X-API#9]

**Comment by rentainhe** [comment]
Hello, we are still refining our API now, thanks a lot for providing this issue, we will release this feature recently.

**Comment by mengyao2022** [comment]
so now, prompt-free feature is not working?

**Comment by rentainhe** [comment]
@mengyao2022 @xyl3902596 We've already update our code to `dds-cloudapi-sdk==0.3.3` and supported the `prompt-free` anything detection demo.
